language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master
  - release-2.7
  - release-2.8
  - release-2.9
  - release-3.0
  - release-3.1

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1
